### ISSUE TITLE
Load bookmark URL in an iframe

### ISSUE THREAD

**Issue by fvsch** [cadeyrn/keep-or-delete-bookmarks#1]
Hi, thanks for a wonderful extension!

I'm wondering if, optionally, the UI could switch to a toolbar or sidebar mode and open the bookmark's URL in an iframe. This could make reviewing bookmarks more effective, at the cost of some bandwidth.

**Comment by PanderMusubi** [comment]
Yes, this saves opening URL in another tab. As far as I am concerned, the Tinder metaphore may be used to the fullest.

**Comment by cadeyrn** [comment]
This is difficult to implement because it's not possible at all for a lot of websites because of their security configuration. So it would work for some websites but not for others.

**Comment by PanderMusubi** [comment]
Might still be worth the effort for the sites that do allow for it.

**Comment by fvsch** [comment]
Another option, for Firefox, is to make the extension work in the sidebar too.
It would require a few code changes and some design changes to accommodate the sidebar's format (narrow and tall).

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Sidebars

**Comment by cadeyrn** [comment]
Thanks for the suggestion. I will close this feature request as "wontfix" for the following reasons:

1. Most times it's not needed to see the website to make the decision.
2. You only need one click to open the website.
3. Since Keep or Delete Bookmarks 2.0 you can also press a key to open the website.
4. Keep or Delete Bookmarks 2.0 checks in real time if the bookmark still works or is broken.
5. Also the date when the bookmark was added to Firefox was implemented in Keep or Delete Bookmarks 2.0.
6. For these reasons it's already easier than ever to make an informed decision whether the bookmark is still needed or not.
7. Therefore I don't see much value in loading the bookmark in an iframe or in a sidebar, at least much less value than in Keep or Delete Bookmarks 1.0.
8. It's not possible for every website anyway.
9. Also I am not convinced how it could be integrated well with the UX concept of Keep or Delete Bookmarks that is: keeping the user interface as simple as possible.

I may reconsider the decision in the future if there are really good arguments.
